linters:
  enable:
    - staticcheck
    - unused
    - decorder
    - errchkjson
    - exhaustruct
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godox
    - lll
    - loggercheck
    - revive
    - sloglint
    - tagalign
    - unparam
    
linters-settings:
  revive:
    config: .revive.toml
  staticcheck:
    checks:
      - "SA"
      
issues:
  format: "format: {{.FromLinter}}: {{.Text}}"
  
